# Generated by Django 4.2.1 on 2023-05-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_bookunstance_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookunstance", options={"ordering": ["due_back"]},
        ),
        migrations.AddField(
            model_name="bookunstance",
            name="due_back",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookunstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Maintenance"),
                    ("o", "On loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                ],
                default="m",
                help_text="Book availability",
                max_length=1,
            ),
        ),
    ]
