# Generated by Django 4.2.2 on 2023-06-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_bookunstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookunstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "set book as returned"),),
            },
        ),
    ]
